name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install sbcl
      run: apt-get install sbcl
    - name: Run test
      run: bash run.sh
